### ISSUE TITLE
Add Customizable Keyboard Shortcuts for Eye Protection Toggle

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/EyeProtection#1]
🚀Feature Request
### Description
*Please describe the problem you are trying to solve.*
Implement a feature that allows users to quickly enable or disable the Eye Protection mode using customizable keyboard shortcuts. Users should be able to configure the key combination from the settings, with a default shortcut provided (e.g., Ctrl+E for toggle). The shortcut settings should be saved and persisted across sessions, allowing users to set their preferred key combinations for convenience. Additionally, ensure that the chosen shortcuts do not conflict with common system or browser shortcuts.

### Why is this feature important to you?
*Is your feature request related to a problem? Please describe.*
Manually toggling the Eye Protection mode can be inconvenient, especially when switching frequently between different lighting conditions.

### Describe the solution you'd like
*Please describe the desired behavoiur.*
Allow users to toggle Eye Protection mode with a default keyboard shortcut (e.g., Ctrl+E). Additionally, provide a settings option where users can customize the shortcut to their preference and save it across sessions.

**Comment by IngaleChinmay04** [comment]
I'm interested in doing it! Can you assign this issue to me?

**Comment by haseeb-555** [comment]
hello mam im interested in doing this can you assign this to me ,

**Comment by haseeb-555** [comment]
hello mam im interested in doing this can you assign this to me ,

**Comment by aachintya** [comment]
ma'am i am done with 60% of the work for all the issues ,if you can assign this to me it would be grateful 
i've also added testing functionality for developers.

**Comment by Nandika-A** [comment]
Assigning this issue to @aachintya on the basis of first request on contrihub's website.

**Comment by Nandika-A** [comment]
Closed as completed via #6
