### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/EyeProtection#2]
# 🚀Feature Request
### Description
The current UI may be uncomfortable for users in low-light environments, leading to eye strain. Implementing a Dark Mode option can enhance user experience by providing a visually softer interface during nighttime or in dimly lit settings.

### Why is this feature important to you?
It’s essential for accessibility and comfort.

### Describe the solution you'd like
Introduce a Dark Mode feature that users can toggle on and off. Include a settings option to allow users to choose their preferred mode (Light, Dark, or Automatic based on system settings).

**Comment by aachintya** [comment]
I can work for the issue. 

**Proposed Solution and Addition : -** 

1. Currently the buttons are of uneven size ,i would like to make them of even size and add basic interactivity to it.
2.  Add a dark theme toggling button on the top right hand corner of the screen

Can you assign this to me ?

**Comment by Nandika-A** [comment]
> I can work for the issue.
> 
> **Proposed Solution and Addition : -**
> 
> 1. Currently the buttons are of uneven size ,i would like to make them of even size and add basic interactivity to it.
> 2. Add a dark theme toggling button on the top right hand corner of the screen
> 
> Can you assign this to me ?

sure, go ahead!

**Comment by Nandika-A** [comment]
@aachintya Are you working on this issue?

**Comment by Nandika-A** [comment]
Closed as completed via #6
