### ISSUE TITLE
Custom time intervals

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/EyeProtection#3]
# 🚀Feature Request

### Description
Currently, the Eye Protection feature may not allow users to customize the time intervals for automatic activation and deactivation (e.g., enabling eye protection during specific hours like nighttime). Users need more flexibility to set custom schedules based on their preferences and daily routines.

### Why is this feature important to you?
A fixed or non-customizable time schedule may not suit every user’s needs. For example, someone working late into the night may want to automatically enable Eye Protection during certain hours.

### Describe the solution you'd like
Allow users to define custom start and end times for when the Eye Protection mode is automatically enabled and disabled. Users should be able to configure this in the settings with a simple time picker UI. The application should remember the schedule and apply it accordingly, enabling/disabling the eye protection at the defined times.

**Comment by aachintya** [comment]
I would like to propose a two tab solution for it, one for managing the normal timer and other to schedule it.
I also noticed there is a bug in the pause button , it doesn't work , i'll fix it also
Also `manifest.json` needs to be updated for the `hourglass.png` icon to load correctly.
I have started working on the issues. Can you assign me this ?

**Comment by Nandika-A** [comment]
Closed as completed via #6
