### ISSUE TITLE
Enable users to write custom alert messages

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/EyeProtection#5]
# 🚀Feature Request

### Description
Currently, the application provides predefined alert messages for reminding users to take eye protection breaks. However, allowing users to write their own custom alert messages would enhance personalization and make the app more flexible for different use cases.

### Why is this feature important to you?
Some users may have specific needs or motivational messages that they find more helpful.

### Describe the solution you'd like
The solution should include a UI element where users can input a custom alert message. This message would then replace the default alert text when break reminders pop up. Ideally, the custom message input would have a character limit to avoid overly long alerts.

### Additional context
An alternative solution could be to allow users to choose from a list of predefined motivational messages, but providing full customization would offer more flexibility.

**Comment by anvesh-singh** [comment]
plz assign this issue to me

**Comment by UjjwalBaranwal** [comment]
i want to contribute to this issue pls assign it to me

**Comment by anvesh-singh** [comment]
while running the extension it is giving the following issue 
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
how to solve this so i can implement custom messages

**Comment by Nandika-A** [comment]
> while running the extension it is giving the following issue Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. how to solve this so i can implement custom messages

It's working for me and other contributors, can you tell how did you set up the extension?

**Comment by anvesh-singh** [comment]
i forked the repo cloned it and unpacked the extension in dev mode in chrome and to see the notification i just changed the timer value from 20 to a minute i found that  the notification is made but the popup never shows for it

**Comment by Nandika-A** [comment]
> i forked the repo cloned it and unpacked the extension in dev mode in chrome and to see the notification i just changed the timer value from 20 to a minute i found that  the notification is made but the popup never shows for it 

Oh okay, I am checking this out.

**Comment by aachintya** [comment]
Notifications are working perfectly.

**Comment by mohitagrawal0412** [comment]
i am facing same problem , notification is not showing when timer is over.
 i added a input form to write custom message of user , then alert is working after clicking on save button ,but notification is still not showing

**Comment by aachintya** [comment]
> i am facing same problem , notification is not showing when timer is over. i added a input form to write custom message of user , then alert is working after clicking on save button ,but notification is still not showing

Refer to the chrome [Extension API documentation](https://developer.chrome.com/docs/extensions/reference/api) for reference. It works fine.

See works perfectly fine

<img width="381" alt="Screenshot 2024-10-10 at 1 04 33 AM" src="https://github.com/user-attachments/assets/2d4a8055-3562-46a6-9cb2-f061d1ab8bfd">

<img width="393" alt="Screenshot 2024-10-10 at 1 04 53 AM" src="https://github.com/user-attachments/assets/c4057082-fd29-4a96-bca3-45596a4f2a6c">

This issue is assigned to someone currently. If he is unable to complete it , i'll request assignment for myself.

**Comment by Nandika-A** [comment]
@mohitagrawal0412, @anvesh-singh try pulling the code, I tested it is also working for me. Contact again if the error persists.

**Comment by Nandika-A** [comment]
Closed as completed via #7
